name: xml_parser
description: An unopinionated XML parser that can read, traverse, modify, and write XML documents.
version: 0.1.2
homepage: https://github.com/james-alex/xml_parser

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  html_character_entities: ^1.0.0+1
  http: ^0.13.0
  recursive_regex: ^1.0.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
